name: Generate GitHub Snake

on:
  push:
    branches:
      - main   # Runs when pushing to the 'main' branch
  pull_request:
    branches:
      - main   # Runs when creating or updating a PR targeting 'main'
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (UTC)

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Upload the generated images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-snake-artifacts
          path: dist/*

      - name: Display generated snake
        run: |
          echo "Generated snake images:"
          echo "  - github-snake.svg"
          echo "  - github-snake-dark.svg"
          echo "  - ocean.gif"
